---

- name: test play
  hosts: all
  become: yes
  vars:
    osquery_version: "4.9.0"
    filebeat_version: "7.17.0"
  tasks:
  - name: cleanup All installed packages 
    yum:
      name: "{{item}}"
      state: absent
      update_cache: yes
    ignore_errors: yes
    with_items:
    - osqueryd
    - jq
    - filebeat
    - td-agent-bit
    - fluent-bit
  
  - name: Remove all configuration files
    file:
      path: "{{item}}" 
      state: absent
    with_items: 
    - /etc/filebeat/
    - /etc/fluent-bit/fluent-bit.conf
    - /etc/td-agent-bit/
    - /etc/osquery
    - /usr/bin/yq
    - /var/log/vminfo
    - /var/log/rsyslog/forwarded-logs.log

  - name: remove /tmp dir contents
    file: path='/tmp/{{ item }}' state=absent
    with_fileglob:
      - /tmp/*   

# remote_host is: name/ip, e.g. 192.168.0.1, port optional e.g. 10514
#Target="remote_host" Port="XXX" Protocol="tcp")

    # for Oracle linux version >= 8
  - name: replace remote host in /etc/rsyslog.conf:8
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: 'Target="10.5.236.52"'
      line: '#Target="remote_host" Port="XXX" Protocol="tcp")'
    when: ansible_distribution_major_version >= '8'   

    # for Oracle linux version >= 8
  - name: replace remote host in /etc/rsyslog.conf:8
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: "@@10.5.236.52:514"
      state: absent
    when: ansible_distribution_major_version < '8'    
    