---
- hosts: all
  become: yes
  tasks:
  - include_role:
      name: ansible-role-fluentbit
    when: ansible_os_family == 'RedHat'
    #when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '8'
