---

# - name: test play
#   hosts: linux
#   tasks:
#   # - debug:
#   #     var: ansible_facts 
#   - debug: 
#       msg: "Oracle linux version 6.10" 
#     when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
#   - debug:
#       msg: "Oracle linux version 7.0"
#     when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
#   - debug:
#       msg: "Oracle linux version 8.0"
#     when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
#   - debug:
#       var: ansible_distribution_major_version
#   - name: test shell
#     shell: "cat /etc/rsyslog.conf | tail -n 5"
#     register: output
#   - debug: 
#       var: output.stdout 

# ---


- name: localhost test
  hosts: localhost
  tasks: 
  - name: test
    ansible.builtin.lineinfile:
      path: /home/opc/ansible/rsyslog
      regexp: '#Target="remote_host"'
      line: Target="10.5.236.52" Port="514" Protocol="tcp"